[build]
    command = "ng build --configuration=netlify"
    publish = "dist/datentria/browser"

[build.environment]
    NODE_VERSION = "20"
    NETLIFY_SKIP_ANGULAR_RUNTIME = "true"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200