[build]
    command = "ng build --configuration=netlify"
    publish = "dist/datentria/browser"

[build.environment]
    NODE_VERSION = "20"

[build.processing]
    skip_processing = false

[[plugins]]
    package = "@netlify/angular-runtime"

    [plugins.inputs]
        standalone = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200